name       : python-sphinxcontrib-htmlhelp
version    : 2.0.0
release    : 4
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-htmlhelp/archive/refs/tags/2.0.0.tar.gz : 4e38da7ea7c762ed676da907e0c65c2dd951b575f35b5b7f700636825e60a35c
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for HTML help files
description: |
    sphinxcontrib-htmlhelp is a sphinx extension which renders HTML help files.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
