name       : python-sphinxcontrib-htmlhelp
version    : 2.0.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/s/sphinxcontrib-htmlhelp/sphinxcontrib-htmlhelp-2.0.0.tar.gz : f5f8bb2d0d629f398bf47d0d69c07bc13b65f75a81ad9e2f71a63d4b7a2f6db2
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for HTML help files
description: |
    sphinxcontrib-htmlhelp is a sphinx extension which renders HTML help files.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
